### ISSUE TITLE
template looks like an ordinary rails template

### ISSUE THREAD

**Issue by adisciple50** [hyperstack-org/hyperstack#336] opened 2021-01-13 21:15 UTC
listed instructions for installation produces the following output.

i did this in windows powershell: 
rails new MyApp -T -m https://rawgit.com/hyperstack-org/hyperstack/edge/install/rails-webpacker.rb
puma
bundle install

and it just looks like an ordinary rails app. the documentation does not tell me to include the rails-hyperstack framework. but i willl do now

**Comment by catmando** [comment] 2021-03-15 18:48
duplicate of #338

**Closed as completed by catmando** 2021-03-15 18:48 UTC
