### ISSUE TITLE
Fix installation instructions

### ISSUE THREAD

**Issue by reedstonefood** [hyperstack-org/hyperstack#307] opened 2020-05-04 19:46 UTC
The [installation instructions](https://github.com/hyperstack-org/hyperstack/blob/edge/install/readme.md#creating-a-new-app-with-a-rails-template) make reference to running this command:

`rails new MyApp -T -m https://rawgit.com/hyperstack-org/hyperstack/edge/install/rails-webpacker.rb`

However, this does not work as rawgit.com was turned off last year.

I believe this should be changed to:

`rails new MyApp -T -m https://raw.githubusercontent.com/hyperstack-org/hyperstack/edge/install/rails-webpacker.rb`

**Comment by barriehadfield** [comment] 2020-05-05 03:21
@reedstonefood thank you for that! I will address this over the weekend, or if you can issue a PR I can accept that change as the docs are built automatically from the readme files.

@catmando is not keen on the Rails template approach so I think we should remove it from the docs. Seems it often creates issues for us.

**Comment by catmando** [comment] 2020-05-05 16:54
@barriehadfield I'm good either way, but I am not going to maintain them is all.  If we keep the templates we should write some specs.  You could adapt them from the generators specs I think.

Also if you keep the templates, I suggest investigating getting the basics of the generator and template to work on the same code files, thus reducing maintenance.

**Comment by reedstonefood** [comment] 2020-05-08 20:43
The website pronounces it can be up and running within 5 minutes. I've been trying for about 5 hours acorss a few days and I don't have a working version yet, because the tutorial is out of date, because of #306 and because of a few other things too. 

For a product that says it makes things easy, I think a template that can get you up and running quickly is important to have. Just my 2c.

**Comment by catmando** [comment] 2021-03-15 20:52
closed as duplicate of #336

**Closed as completed by catmando** 2021-03-15 20:52 UTC
